### ISSUE TITLE
第三章3.3身份证号码的识别代码和数据相关问题

### ISSUE THREAD

**Issue by Freshield** [ocrbook/ocrinaction#10]
首先由于没有训练数据这里的训练没法测试，还是希望能给个相关的训练数据的链接
其次测试数据idcard1.jpg和78页的测试示例图不一样
然后在函数verticle_projection中，以76页为例(感觉这个函数在各个文件中都一样，是不是应该单独放出来调用减少冗余？)
第39行，按照这里的缩进会对每个i都生成一个roi_img，但是我理解这里应该是要按照波峰波谷来进行裁剪，所以缩进应该是再elif中
但是如果使用这个函数对测试数据idcard1.jpg进行处理会发现，这里会把整个图除了边缘的部分以外的地方都变成一个roi_img，没有达到分割的目的。也就是说，理论上用这个函数对于idcard1.jpg图片是没法达到测试的结果。
希望得到反馈和讨论，谢谢

**Comment by FakerYFX** [comment]
感谢您的回复。1.关于身份证数据集的话，这块可能涉及到用户隐私问题，我们不太方便提供，希望您能够理解 2.测试数据给到的也只是一个示例图片(非真实身份证图片) 3.verticle_projection这个函数确实可以单独拿出来减少冗余 4.第39行的代码确实是对每个i都生成一个roi_img，代码本身没有问题
